apiVersion: api.core.anaisurl.com/v1alpha1
kind: Configuration
metadata:
  name: configuration-sample
spec:
  containerPort: 60
  imageTag: "latest"
  limits: "600m"
  readOnlyRootFilesystem: false
  requests:  "300m"
  runAsNonRoot: false
  memoryrequests: "65Mi"
  memorylimits: "130Mi"